apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-pod
  template:
    metadata:
      labels:
        app: broken-pod
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ["sh", "-c", "exit 1;"]
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - "exit 1"
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - "exit 1"
            initialDelaySeconds: 5
            periodSeconds: 5