# SPDX-FileCopyrightText: (C) 2021 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

IMAGE := scenescape-analytics

include ../common.mk

.PHONY: test-build
test-build:
	$(MAKE) IMAGE="scenescape-analytics-test" TARGET="scenescape-analytics-test"
