# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Intel Corporation

# Build k6 with the xk6-mqtt extension for MQTT load testing.
# xk6 Docker tag 1.4.3 bundles xk6 Go module v1.4.3.
# See: https://github.com/grafana/xk6/releases/tag/v1.4.3
FROM grafana/xk6:1.4.6@sha256:1c0bc5c7156069a4c14dd9cdb213e5a67dd760e656e17decb8b0e87889dcf57d AS builder
ARG http_proxy
ARG https_proxy
ARG no_proxy
RUN xk6 build --with github.com/pmalhaire/xk6-mqtt@v0.40.3

FROM scratch
COPY --from=builder /xk6/k6 /usr/bin/k6
USER 65532:65532
HEALTHCHECK CMD ["/usr/bin/k6", "version"]
ENTRYPOINT ["k6"]
