version: 2
updates:
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Github Actions"
    groups:
      github-actions-dependency:
        applies-to: version-updates
        patterns:
          - "*"
    reviewers:
      - "saratpoluri"
      - "dmytroye"

  # Enable version updates for Helm charts
  - package-ecosystem: "helm"
    directories:
      - "/kubernetes/scenescape-chart"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "Helm charts"
    reviewers:
      - "saratpoluri"
      - "dmytroye"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directories:
      - "/controller/docker/Dockerfile"
      - "/controller/robot_vision/Dockerfile"
      - "/docker/Dockerfile"
      - "/autocalibration/docker/Dockerfile"
      - "/percebro/docker/Dockerfile"
      - "/docker/Dockerfile-sources"
      - "/docker/Dockerfile-model-installer"
      - "/docker/Dockerfile-broker"
      - "/docker/Dockerfile-interface"
      - "/kubernetes/init-images/Dockerfile-secrets"
      - "/kubernetes/init-images/Dockerfile-models"
      - "./kubernetes/init-images/Dockerfile-tests"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "Dockerfile"
    reviewers:
      - "saratpoluri"
      - "dmytroye"