
# SPDX-FileCopyrightText: (C) 2023 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# --- Builder stage ---
FROM python:3.13-slim@sha256:4c2cf9917bd1cbacc5e9b07320025bdb7cdf2df7b0ceaccb55e9dd7e30987419 AS builder

WORKDIR /root

RUN apt-get update && apt-get install -y --no-install-recommends wget && rm -rf /var/lib/apt/lists/*

COPY model_installer/src/install-omz-models model_installer/requirements-runtime.txt model_installer/src/copy-config-files .
COPY dlstreamer-pipeline-server dlstreamer-pipeline-server

RUN pip install --no-cache-dir -r requirements-runtime.txt

ENV MODEL_DIR=/root/models
RUN python install-omz-models --default --precisions FP32
RUN python copy-config-files /root /root/models

# --- Runtime stage ---
FROM busybox:1.37@sha256:d82f458899c9696cb26a7c02d5568f81c8c8223f8661bb2a7988b269c8b9051e

WORKDIR /root

COPY --from=builder /root/models /root/models
COPY sample_data /root/sample_data
COPY controller/config/tracker-config.json /root/controller/tracker-config.json

CMD ["/bin/sh"]
