# -*- mode: Fundamental; indent-tabs-mode: nil -*-

# SPDX-FileCopyrightText: (C) 2024 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# This file is licensed under the Limited Edge Software Distribution License Agreement.

FROM busybox

COPY tests /root/tests

CMD ["/bin/sh"]
