
# SPDX-FileCopyrightText: (C) 2023 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# --- Builder stage ---
FROM python:3.12-slim AS builder

WORKDIR /root

COPY model_installer/src/install-omz-models .
COPY percebro/config/model-config.json .

ENV MODEL_DIR=/root/models
ENV MODEL_CONFIGFILE=/root/model-config.json
RUN python install-omz-models --default --precisions FP32

# --- Runtime stage ---
FROM busybox:1.37

WORKDIR /root

COPY --from=builder /root/models /root/models
COPY sample_data /root/sample_data
COPY controller/config/tracker-config.json /root/controller/tracker-config.json

CMD ["/bin/sh"]
