#!/usr/bin/env python3

# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

import json
import subprocess
import pprint
import fileinput
import re
from pathlib import Path
from time import sleep

REUSE_FILE = 'reuse_lint.json'


def add_license_to_file(file_path):
    if Path(file_path).suffix == '':
        with open(file_path, 'r') as f:
            first_line = f.readline().strip()
            if first_line == "#!/usr/bin/env python3" or first_line == "#!/bin/bash":
                subprocess.run(["make", f"add-licensing", "FILE=" + item, "ADDITIONAL_LICENSING_ARGS=" + "\"--style=python\""])
            else:
                subprocess.run(["make", "add-licensing", "FILE=" + item])
    elif Path(file_path).suffix == '.template':
        subprocess.run(["make", f"add-licensing", "FILE=" + item, "ADDITIONAL_LICENSING_ARGS=" + "\"--style=yaml\""])
    elif file_path.contains('Dockerfile') or file_path.contains('Makefile'):
        subprocess.run(["make", "add-licensing", "FILE=" + item, "ADDITIONAL_LICENSING_ARGS=" + "\"--style=python\""])
    else:
        subprocess.run(["make", "add-licensing", "FILE=" + item])

subprocess.run(["reuse", "lint", "-j", REUSE_FILE])

with open(REUSE_FILE, 'r') as f:
    data = json.load(f)

for item in data.get("non_compliant").get("missing_licensing_info", []):
    if item in data.get("non_compliant").get("missing_copyright_info", []):
        add_license_to_file(item)
    else:
        for line in fileinput.input(item, inplace=True):
            if re.match(r'.*Copyright \(C\).*',line):
                print('{}'.format(line.replace("Copyright (C)","SPDX-FileCopyrightText: (C)")),end='')
            else:
                print('{}'.format(line),end='')
        add_license_to_file(item)
