# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# prefix for volume and container names, override with the environment variable COMPOSE_PROJECT_NAME
name: scenescape

networks:
  scenescape:

secrets:
  root-cert:
    file: ${SECRETSDIR}/certs/scenescape-ca.pem
  broker-cert:
    file: ${SECRETSDIR}/certs/scenescape-broker.crt
  broker-key:
    file: ${SECRETSDIR}/certs/scenescape-broker.key
  web-cert:
    file: ${SECRETSDIR}/certs/scenescape-web.crt
  web-key:
    file: ${SECRETSDIR}/certs/scenescape-web.key
  vdms-client-cert:
    file: ${SECRETSDIR}/certs/scenescape-vdms-c.crt
  vdms-client-key:
    file: ${SECRETSDIR}/certs/scenescape-vdms-c.key
  vdms-server-cert:
    file: ${SECRETSDIR}/certs/scenescape-vdms-s.crt
  vdms-server-key:
    file: ${SECRETSDIR}/certs/scenescape-vdms-s.key
  django:
    file: ${SECRETSDIR}/django
  percebro.auth:
    file: ${SECRETSDIR}/percebro.auth
  controller.auth:
    environment: CONTROLLER_AUTH
  browser.auth:
    file: ${SECRETSDIR}/browser.auth
  calibration.auth:
    file: ${SECRETSDIR}/calibration.auth

services:

  retail-video:
    image: scenescape-percebro:${VERSION:-latest}
    init: true
    networks:
      scenescape:
    command:
      - "percebro"
      - "--camera=sample_data/apriltag-cam1.mp4"
      - "--cameraid=camera1"
      - '--intrinsics={"fov":70}'
      - "--camera=sample_data/apriltag-cam2.mp4"
      - "--cameraid=camera2"
      - '--intrinsics={"fov":70}'
      - "--camerachain=retail"
      - "--debug"
      - "--stats"
    devices:
      - "/dev/dri:/dev/dri"
    volumes:
      - vol-models:/opt/intel/openvino/deployment_tools/intel_models
      - vol-sample-data:/home/scenescape/SceneScape/sample_data
    secrets:
      - source: root-cert
        target: certs/scenescape-ca.pem
      - percebro.auth
    restart: always

configs:
  # uncomment this section when using eclipe mosquitto broker
  # mosquitto-secure:
  #   file: ./dlstreamer-pipeline-server/mosquitto/mosquitto-secure.conf
  tracker-config:
    file: ./controller/config/tracker-config.json

volumes:
  vol-db:
  vol-media:
  vol-migrations:
  vol-datasets:
  vol-sample-data:
  vol-models:
  vol-netvlad_models:
    driver: local
