# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

version = 1

[[annotations]]
path = [
  "**/mp4",
  "**/*.md",
  "**/*.json",
  "**/VERSION",
  ".github/ISSUE_TEMPLATE/*",
  ".gitignore",
]
SPDX-FileCopyrightText = "(C) 2025 Intel Corporation"
SPDX-License-Identifier = "LicenseRef-Intel-Edge-Software"