# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

IMAGE := intel/scenescape-reid
TARGET := scenescape-reid-runtime
USES_SCENE_COMMON := yes

include ../common.mk
