# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

define metric-recipe =
	$(eval TEST_SCRIPT=$1)
	$(eval TEST_SUITE=$2)
	$(eval LOGFILE=$(TEST_DATA)/smoke/$@-$(shell date -u +"%F-%T").log)
	@set -ex \
	  ; echo RUNNING METRIC TEST $@ \
	  ; if [ -n "$3" ]; then \
	        FRAME_RATE="--camera_frame_rate $3" \
	  ; fi \
	  ; if [ -n "$4" ]; then \
	        KFILTER="-k $4" \
	  ; fi \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; tools/scenescape-start --image ${IMAGE}-controller-test pytest -s $(GENERATE_JUNITXML) $(TEST_SCRIPT) \
	                                   $${FRAME_RATE} $${KFILTER} \
	                                   -o junit_suite_name=$(TEST_SUITE) | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@
endef

distance-msoce: # NEX-T10524
	$(call metric-recipe, tests/system/metric/tc_distance_thresh.py, distance-threshold)

idc-error-metric:
	$(call metric-recipe, tests/system/metric/tc_tracker_metric.py, idc-metric, 30, test_idc_error_metric)
	$(call metric-recipe, tests/system/metric/tc_tracker_metric.py, idc-metric, 10, test_idc_error_metric)

msoce-metric:
	$(call metric-recipe, tests/system/metric/tc_tracker_metric.py, msoce-metric, 30, test_msoce_metric)
	$(call metric-recipe, tests/system/metric/tc_tracker_metric.py, msoce-metric, 10, test_msoce_metric)

velocity-metric:
	$(call metric-recipe, tests/system/metric/tc_tracker_metric.py, velocity-metric, 30, test_velocity_metric)
	$(call metric-recipe, tests/system/metric/tc_tracker_metric.py, velocity-metric, 10, test_velocity_metric)

metrics: idc-error-metric msoce-metric velocity-metric # NEX-T10463
