# SPDX-FileCopyrightText: (C) 2021 - 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Unit test targets. Each target invokes pytest with -k <test_id>.
# Standalone unit tests (formerly unit-recipe) are defined in tests/test_unit.py;
# compose-based unit tests (formerly unit-docker-compose-recipe) use the
# scenescape_env fixture via tests/conftest.py.
#

SSCAPE_TESTS_PATH=tests/sscape_tests

# Recipes below must be in alphabetical order

account-security-unit:
	$(call pytest-recipe, account_security_unit)

autocamcalib-unit: # NEX-T10459
	$(call pytest-recipe, autocamcalib_unit)

cam-unit:
	$(call pytest-recipe, cam_unit)

geometry-unit: # NEX-T10454
	$(call pytest-recipe, geometry_unit)

geospatial-unit: # NEX-T17406
	$(call pytest-recipe, geospatial_unit)

markerless-unit: # NEX-T10497
	$(call pytest-recipe, markerless_unit)

# TODO: mapping-unit uses a plain docker run.
# It is not yet migrated to the pytest model.
mapping-unit:
	$(eval LOGFILE=$(TEST_DATA)/unit/$@-$(shell date -u +"%F-%T").log)
	@set -exo pipefail \
	  ; echo RUNNING TEST $@ \
	  ; cd .. \
	  ; mkdir -p $(shell dirname $(LOGFILE)) \
	  ; docker run --rm \
	      --entrypoint pytest \
	      -w /home/scenescape/SceneScape/tests \
	      $(IMAGE)-mapping-test:$(VERSION) \
	      -v $(GENERATE_JUNITXML_UNITTEST) 2>&1 | tee -i $(LOGFILE) \
	  ; echo "MAKE_TARGET: $@" | tee -ia $(LOGFILE) \
	  ; echo END TEST $@

mesh-util-unit:
	$(call pytest-recipe, mesh_util_unit)

robot-vision-unit:
	$(call pytest-recipe, robot_vision_unit)

scene-unit: # NEX-T10451
	$(call pytest-recipe, scene_unit)

scenescape-unit: # NEX-T10450
	$(call pytest-recipe, scenescape_unit)

schema-unit: # NEX-T10458
	$(call pytest-recipe, schema_unit)

singleton-sensor-unit:
	$(call pytest-recipe, singleton_sensor_unit)

timestamp-unit: # NEX-T10480
	$(call pytest-recipe, timestamp_unit)

transform-unit: # NEX-T17405
	$(call pytest-recipe, transform_unit)

uuid-manager-unit: # NEX-T19884
	$(call pytest-recipe, uuid_manager_unit)

vdms-adapter-unit: # NEX-T19885
	$(call pytest-recipe, vdms_adapter_unit)

views-unit: # NEX-T10479
	$(call pytest-recipe, views_unit)
