pipeline:
  output:
    path: /tmp/tracker-evaluation # Base output directory

dataset:
  class: datasets.unity_dataset.UnityDataset
  config:
    data_path: ../../../tests/system/metric/unity_dataset
    cameras: [Cam_x1_0, Cam_x2_0]
    camera_fps: 30

harness:
  class: harnesses.scene_controller_harness.SceneControllerHarness
  config:
    container_image: intel/scenescape-controller:latest
    tracker_config_path: /home/fst/GT_TrackEval_Scenescape/tools/tracker/evaluation/pipeline_configs/black_box_unity/config/controller_immediate.json

evaluators:
  - class: evaluators.trackeval_evaluator.TrackEvalEvaluator
    config:
      metrics: [HOTA, MOTA, IDF1]
  - class: evaluators.diagnostic_evaluator.DiagnosticEvaluator
    config:
      metrics: [LOC_T_X, LOC_T_Y, DIST_T]
  - class: evaluators.jitter_evaluator.JitterEvaluator
    config:
      metrics:
        [
          rms_jerk,
          rms_jerk_gt,
          rms_jerk_ratio,
          acceleration_variance,
          acceleration_variance_gt,
          acceleration_variance_ratio,
        ]
