# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Default listener on port 1883
listener 1883

# Allow anonymous connections
allow_anonymous true

# Persistence
persistence false
