#!/bin/bash

# SPDX-FileCopyrightText: (C) 2022 - 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

PERF_TEST_BASE=tests/perf_tests
COMPOSE=tests/compose
COMPOSE_DLS=tests/compose/dlstreamer

TEST_NAME="Scene Performance test"

source tests/test_utils.sh

export VERSION=1.4.0-alpha
export IMAGE="scenescape-manager-test:${VERSION}"


export SECRETSDIR=/workspace/secrets
export DBROOT=test_data/scene_perf_full
export EXAMPLEDB=tests/testdb.tar.bz2

export WAITFORCONTAINERS="pgserver web scene "
export LOGSFORCONTAINER="${WAITFORCONTAINERS} "

RUNFILE=test_scene_perf.txt

#Run the scene performance test.
echo -------Test execution------------
tests/runtest ${COMPOSE_DLS}/broker.yml:${COMPOSE}/ntp.yml:${COMPOSE_DLS}/pgserver.yml:${COMPOSE_DLS}/retail_video.yml:${COMPOSE_DLS}/queuing_video.yml:${COMPOSE_DLS}/scene.yml:${COMPOSE_DLS}/web.yml dlstreamer-pipeline-server/testperf  > ${RUNFILE} 2>&1

RESULT=$?

if [[ $RESULT -eq 0 ]]
then
    echo "${TEST_NAME}: Test Passed"
else
    echo "${TEST_NAME}: Test Failed"
fi

exit $RESULT
