---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

misconfiguration:
  helm:
    set:
      - supass=demo
  skip-files:
    - "scene_common/Dockerfile"
    - "tests/security/fuzzing/Dockerfile"
