# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.vdms.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vdms-dep
  labels:
    app: {{ .Release.Name }}-vdms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-vdms
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vdms
    spec:
      shareProcessNamespace: true
      containers:
        - image: intellabs/vdms:latest
          name: {{ .Release.Name }}-vdms
          env:
          - name: OVERRIDE_ca_file
            value: /run/secrets/certs/scenescape-ca.pem
          - name: OVERRIDE_cert_file
            value: /run/secrets/certs/scenescape-vdms-s.crt
          - name: OVERRIDE_key_file
            value: /run/secrets/certs/scenescape-vdms-s.key
            {{- include "proxy_envs" . | indent 10 }}
          imagePullPolicy: Always
          resources: {}
          volumeMounts:
          - mountPath: /run/secrets/certs
            name: certs
            readOnly: true
      restartPolicy: Always
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: certs
        projected:
          sources:
          - secret:
              name: {{ .Release.Name }}-broker-tls
              items:
              - key: tls.crt
                path: broker-cert
              - key: tls.key
                path: broker-key
          - secret:
              name: {{ .Release.Name }}-vdms-tls
              items:
              - key: tls.key
                path: scenescape-vdms-s.key
              - key: tls.crt
                path: scenescape-vdms-s.crt
          - secret:
              name: {{ .Release.Name }}-scenescape-ca.pem
              items:
              - key: tls.crt
                path: scenescape-ca.pem
status: {}
{{- end }}
