# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
# Modifications:
# Nokia VPOD (Emerging Products, BLR), 2026

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sscape-adapter
data:
  sscape_adapter.py: |
{{ .Files.Get "files/dlsps/sscape_adapter.py" | indent 4 }}
  sscape_policies.py: |
{{ .Files.Get "files/dlsps/sscape_policies.py" | indent 4 }}
  sscape_3d_detector.py: |
{{ .Files.Get "files/dlsps/sscape_3d_detector.py" | indent 4 }}
  triton_inference_base.py: |
{{ .Files.Get "files/dlsps/triton_inference_base.py" | indent 4 }}
  yolov7_triton_inference.py: |
{{ .Files.Get "files/dlsps/yolov7_triton_inference.py" | indent 4 }}
  yolox_triton_inference.py: |
{{ .Files.Get "files/dlsps/yolox_triton_inference.py" | indent 4 }}
