name: 'Cleanup Action'
description: 'Clean runner environment after build/test'
runs:
  using: "composite"
  steps:
  - name: "Stop all running Docker containers"
    if: always()
    run: |
      docker ps -aq | xargs docker rm -f  || true

  - name: "Remove all volumes used in test"
    if: always()
    run: |
      docker volume ls -q | xargs docker volume rm -f  || true

  - name: "Clean runner"
    if: always()
    run: |
      sudo rm -rf *  || true

