# SPDX-FileCopyrightText: (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "Upload Logs and Reports"
description: "Renames logs and uploads logs and reports as artifacts"

inputs:
  name:
    description: "Artifact name suffix (unique per job/matrix)"
    required: false
    default: ${{ github.job }}

  reports_path:
    description: "Globs for test report files"
    required: false
    default: |
      tests/**/test_reports/**/*.html
      tests/**/test_reports/**/*.xml

  logs_path:
    description: "Globs for test log files"
    required: false
    default: |
      **/test_data/**/*.log

runs:
  using: "composite"
  steps:
    - name: Rename logs to remove colons
      shell: bash
      run: |
        set +e
        find . -type f -path "**/test_data/*.log" | while read -r file; do
          newfile="$(dirname "$file")/$(basename "$file" | tr ':' '-')"
          if [ "$file" != "$newfile" ]; then
            mv "$file" "$newfile"
          fi
        done
        exit 0

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports-${{ inputs.name }}
        path: ${{ inputs.reports_path }}
        if-no-files-found: ignore
        retention-days: 14

    - name: Upload Test Logs
      uses: actions/upload-artifact@v4
      with:
        name: test-logs-${{ inputs.name }}
        path: ${{ inputs.logs_path }}
        if-no-files-found: ignore
        retention-days: 14
