# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# This file is licensed under the Limited Edge Software Distribution License Agreement.

IMAGE := scenescape-broker
RUNTIME_OS_IMAGE := debian:stable-slim
HAS_PIP := ""

include ../common.mk
