# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-init-sample-data
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.hooks.enabled }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    {{- if not .Values.chartdebug }}
    "helm.sh/hook-delete-policy": hook-succeeded
    {{- end }}
    {{- end }}
spec:
  template:
    spec:
      initContainers:
      - name: download-sample-data
        command: ["/bin/bash", "-c"]
        image: busybox
        args:
        - |
          set -euo pipefail
          if [ -f /workspace/sample_data/.done ]; then
              echo ".done file exists in /data/videos"
          else
              echo ".done file does NOT exist in /workspace/sample_data/"
              echo "Downloading videos from GitHub..."
              apk add --no-cache wget
              mkdir -p /workspace/sample_data
              SAMPLE_DATA_URL="{{ .Values.sample_data.source }}/tree/{{ .Values.sample_data.sourceVersion }}/{{ .Values.sample_data.sourceDir }}"
              FILES="{{ join " " .Values.sampleData.files }}"
              for file in $FILES; do
                  echo "Downloading $file..."
                  wget -O "/workspace/sample-data-storage/$file" "$SAMPLE_DATA_URL/$file"
              done
              echo "Sample data downloaded successfully"
          fi
        volumeMounts:
        - mountPath: /workspace/sample-data-storage
          name: sample-data-storage
      - name: convert-videos
        image: linuxserver/ffmpeg:version-8.0-cli
        command: ["/bin/bash", "-c"]
        args:
        - |
          set -euo pipefail
          echo "Converting .mp4 files to .ts..."
          for mp4_file in /workspace/sample-data-storage/*.mp4; do
              ts_file="${mp4_file%.mp4}.ts"
              echo "Converting $mp4_file to $ts_file..."
              /ffmpegwrapper.sh -i "$mp4_file" -c copy "$ts_file"
          done
          touch /workspace/sample-data-storage/.done
        volumeMounts:
        - mountPath: /workspace/sample-data-storage
          name: sample-data-storage
      containers:
      - command: ["/bin/bash", "-c"]
        args:
        - |
          set -euo pipefail
          echo "Copying sample data, tracker-config.json, videos..."

          # Copy tracker config
          if [ -f "/workspace/controller/tracker-config.json" ]; then
            mkdir -p /workspace/controller-storage
            cp /workspace/controller/tracker-config.json /workspace/controller-storage/tracker-config.json
            echo "Copied tracker-config.json file."
          else
            echo "Warning: /workspace/controller/tracker-config.json not found"
          fi

          echo "Sample data setup completed successfully"
        image: busybox
        name: {{ .Release.Name }}-{{ .Values.initModels.image }}-container
        imagePullPolicy: Always
        env:
          {{ include "proxy_envs" . | indent 12 }}
        volumeMounts:
        - mountPath: /workspace/sample-data-storage
          name: sample-data-storage
        - mountPath: /workspace/controller-storage
          name: controller-storage
        - mountPath: /workspace/videos-storage
          name: videos-storage
        - mountPath: /workspace/controller/
          name: tracker-config
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: sample-data-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-sample-data-pvc
      - name: controller-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-controller-pvc
      - name: videos-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-videos-pvc
      - name: tracker-config
        configMap:
          name: {{ .Release.Name }}-tracker-config
  backoffLimit: 3
