---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "Setup Test Environment"
description: "Install Pytest and dependencies for testing, setup Docker and Python"
inputs:
  dockerhub-token:
    description: 'DockerHub token'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.12"
        check-latest: true

    - name: "Log in to DockerHub"
      uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        username: scenescape
        password: ${{ inputs.dockerhub-token }}

    - name: Set up Docker
      uses: docker/setup-docker-action@v5
      with:
        daemon-config: |
          {
            "features": {
              "containerd-snapshotter": false
            }
          }

    - name: Install firefox
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox

    - name: Set up geckodriver
      shell: bash
      run: |
        GECKODRIVER_VERSION=$(curl -sL https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
        wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
        tar -xvzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
        sudo mv geckodriver /usr/local/bin/

    - name: "Setup Test Environment"
      shell: bash
      run: |
        make && make setup-tests

    - name: "Install github annotate plugin"
      shell: bash
      run: |
        source tests/.venv/bin/activate
        pip install -r .github/resources/requirements-pytest.txt
