# -*- mode: Fundamental; indent-tabs-mode: nil -*-

# SPDX-FileCopyrightText: (C) 2024 - 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

# Auto-generated by tools/dependencies/generate_dockerfile_artifacts.py
# Annotated version: comments show which binary packages from
# updated-dependencies.csv are covered by each source entry.

FROM debian:12 AS source-grabber

RUN echo "deb-src http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware" >> /etc/apt/sources.list \
    && echo "deb-src http://security.debian.org/debian-security bookworm-security main" >> /etc/apt/sources.list \
    && echo "deb-src http://deb.debian.org/debian bookworm-updates main" >> /etc/apt/sources.list \
    && echo "deb-src http://deb.debian.org/debian trixie main contrib non-free non-free-firmware" >> /etc/apt/sources.list
RUN apt-get update && apt-get install -y --no-install-recommends dpkg-dev

WORKDIR /sources-deb
RUN apt-get source --download-only \
    # libarmadillo11:1:11.4.2+dfsg-1
    armadillo \
    # bindfs:1.14.7-1
    bindfs \
    # libcfitsio10:amd64:4.2.0-3
    cfitsio \
    # libelf1:amd64:0.188-2.1
    elfutils \
    # fuse:2.9.9-6+b1
    # libfuse2:amd64:2.9.9-6+b1
    fuse \
    # libfyba0:amd64:4.1.1-8
    fyba \
    # libgfortran5:amd64:12.2.0-14+deb12u1
    # libgomp1:amd64:12.2.0-14+deb12u1
    # libgomp1:amd64:14.2.0-19
    # libquadmath0:amd64:12.2.0-14+deb12u1
    gcc-12 \
    # libgcc-s1:amd64:14.2.0-19
    # libstdc++6:amd64:14.2.0-19
    gcc-14 \
    # gdal-plugins:3.6.2+dfsg-1+b2
    # libgdal32:3.6.2+dfsg-1+b2
    gdal \
    # libgdbm-compat4:amd64:1.23-3
    gdbm \
    # libgdcm3.0:amd64:3.0.21-1
    gdcm \
    # libgeos-c1v5:amd64:3.11.1-1
    # libgeos3.11.1:amd64:3.11.1-1
    geos \
    # libglib2.0-0:amd64:2.74.6-2+deb12u8
    glib2.0 \
    # libc6:amd64:2.41-12+deb13u1
    glibc \
    # libhdf5-103-1:amd64:1.10.8+repack1-1
    # libhdf5-hl-100:amd64:1.10.8+repack1-1
    hdf5 \
    # libicu72:amd64:72.1-3+deb12u1
    icu \
    # libjbig0:amd64:2.1-6.1
    jbigkit \
    # libjson-c5:amd64:0.16-2
    json-c \
    # libde265-0:amd64:1.0.11-1+deb12u2
    libde265 \
    # libgudev-1.0-0:amd64:237-2
    libgudev \
    # libhdf4-0-alt:4.2.15-5
    libhdf4 \
    # libheif1:amd64:1.15.1-1+deb12u1
    libheif \
    # libinput-bin:1.22.1-1
    # libinput10:amd64:1.22.1-1
    libinput \
    # libkmlbase1:amd64:1.3.0-10
    # libkmldom1:amd64:1.3.0-10
    # libkmlengine1:amd64:1.3.0-10
    libkml \
    # librttopo1:amd64:1.1.0-3
    librttopo \
    # libwebp7:amd64:1.2.4-0.2+deb12u1
    # libwebpmux3:amd64:1.2.4-0.2+deb12u1
    libwebp \
    # libsensors-config:1:3.6.0-7.1
    # libsensors5:amd64:1:3.6.0-7.1
    lm-sensors \
    # libmariadb3:amd64:1:10.11.14-0+deb12u2
    # mariadb-common:1:10.11.14-0+deb12u2
    # mysql-common:5.8+1.1.0
    mariadb \
    # media-types:10.0.0
    media-types \
    # libmosquitto1:amd64:2.0.11-1.2+deb12u2
    # mosquitto-clients:2.0.11-1.2+deb12u2
    mosquitto \
    # libnetcdf19:amd64:1:4.9.0-3+b1
    netcdf \
    # libnuma1:amd64:2.0.16-1
    numactl \
    # libogdi4.1:4.1.0+ds-6
    ogdi-dfsg \
    # libopencv-calib3d406:amd64:4.6.0+dfsg-12
    # libopencv-contrib406:amd64:4.6.0+dfsg-12
    # libopencv-core406:amd64:4.6.0+dfsg-12
    # libopencv-dnn406:amd64:4.6.0+dfsg-12
    # libopencv-features2d406:amd64:4.6.0+dfsg-12
    # libopencv-flann406:amd64:4.6.0+dfsg-12
    # libopencv-highgui406:amd64:4.6.0+dfsg-12
    # libopencv-imgcodecs406:amd64:4.6.0+dfsg-12
    # libopencv-imgproc406:amd64:4.6.0+dfsg-12
    # libopencv-ml406:amd64:4.6.0+dfsg-12
    # libopencv-objdetect406:amd64:4.6.0+dfsg-12
    # libopencv-stitching406:amd64:4.6.0+dfsg-12
    # libopencv-video406:amd64:4.6.0+dfsg-12
    opencv \
    # libperl5.36:amd64:5.36.0-7+deb12u3
    # perl-modules-5.36:5.36.0-7+deb12u3
    # perl:5.36.0-7+deb12u3
    perl \
    # libpoppler126:amd64:22.12.0-2+deb12u1
    poppler \
    # libproc2-0:amd64:2:4.0.2-3
    # procps:2:4.0.2-3
    procps \
    # libprotobuf32:amd64:3.21.12-3
    protobuf \
    # libpython3.11-minimal:amd64:3.11.2-6+deb12u6
    # libpython3.11-stdlib:amd64:3.11.2-6+deb12u6
    # libpython3.11:amd64:3.11.2-6+deb12u6
    # python3.11-minimal:3.11.2-6+deb12u6
    # python3.11:3.11.2-6+deb12u6
    python3.11 \
    # libqt5core5a:amd64:5.15.8+dfsg-11+deb12u3
    # libqt5dbus5:amd64:5.15.8+dfsg-11+deb12u3
    # libqt5gui5:amd64:5.15.8+dfsg-11+deb12u3
    # libqt5network5:amd64:5.15.8+dfsg-11+deb12u3
    # libqt5opengl5:amd64:5.15.8+dfsg-11+deb12u3
    # libqt5test5:amd64:5.15.8+dfsg-11+deb12u3
    # libqt5widgets5:amd64:5.15.8+dfsg-11+deb12u3
    qtbase-opensource-src \
    # librtmp1:amd64:2.4+20151223.gitfa8646d.1-2+b2
    rtmpdump \
    # libsocket++1:amd64:1.12.13+git20131030.5d039ba-1+b1
    socket++ \
    # libspatialite7:amd64:5.0.1-3
    spatialite \
    # libsuperlu5:amd64:5.3.0+dfsg1-2+b1
    superlu \
    # libodbc2:amd64:2.3.11-2+deb12u1
    # libodbcinst2:amd64:2.3.11-2+deb12u1
    # unixodbc-common:2.3.11-2+deb12u1
    unixodbc \
    # wget:1.21.3-1+deb12u1
    wget \
    # libx265-199:amd64:3.5-2+b1
    x265 \
    # libxerces-c3.2:amd64:3.2.4+debian-1
    xerces-c \
    # libz3-4:amd64:4.8.12-3.1
    z3

WORKDIR /sources-python
RUN apt-get update && apt-get install --no-install-recommends -y ca-certificates git
RUN : \
    # certifi==2026.2.25
    ; git clone --depth 1 https://github.com/certifi/python-certifi \
    # plyfile==1.0.3
    ; git clone --depth 1 https://github.com/dranjan/python-plyfile \
    # paho-mqtt==2.1.0
    ; git clone --depth 1 https://github.com/eclipse-paho/paho.mqtt.python \
    # bidict==0.23.1
    ; git clone --depth 1 https://github.com/jab/bidict \
    # psycopg2-binary==2.9.11
    ; git clone --depth 1 https://github.com/psycopg/psycopg2 \
    # tqdm==4.67.3
    ; git clone --depth 1 https://github.com/tqdm/tqdm

WORKDIR /sources-conan
RUN : \
    # autoconf/2.71
    ; git clone --depth 1 https://github.com/autotools-mirror/autoconf \
    # automake/1.16.5
    ; git clone --depth 1 https://github.com/autotools-mirror/automake \
    # libtool/2.4.7
    ; git clone --depth 1 https://github.com/autotools-mirror/libtool \
    # m4/1.4.19
    ; git clone --depth 1 https://github.com/autotools-mirror/m4 \
    # paho-mqtt-c/1.3.13
    ; git clone --depth 1 https://github.com/eclipse/paho.mqtt.c \
    # paho-mqtt-cpp/1.5.3
    ; git clone --depth 1 https://github.com/eclipse/paho.mqtt.cpp \
    # eigen/3.4.0
    ; git clone --depth 1 https://github.com/eigenteam/eigen-git-mirror \
    # gnu-config/cci.20210814
    ; git clone --depth 1 https://github.com/gcc-mirror/gcc

WORKDIR /sources-other
RUN : \
    ; git clone --depth 1 https://github.com/mozilla/geckodriver \
    ; git clone --depth 1 https://github.com/mirror/busybox

FROM debian:13

COPY --from=source-grabber /sources* /sources
COPY third-party-programs.txt /sources
WORKDIR /sources

USER nobody
