---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

name: "Build Images"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions:
  contents: read # needed for actions/checkout

jobs:
  build-images:
    name: "Run required linters"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: '3.13'

      - name: "Cache Python Virtualenv"
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.github/resources/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}

      - name: Run Submodule Secrets and Certificates Initialization
        run: |
          make clean-all
          make -C tools/certificates clean
          make init-secrets

      - name: Build scene_common
        run: |
          git status
          make -C scene_common

      - name: Run All Tests
        run: |
          rm -rf venv
          python3 -m venv venv
          source $PWD/venv/bin/activate
          echo "$PWD/venv/bin" >> $GITHUB_PATH
          pip install --upgrade pip
          pip install -r .github/resources/requirements.txt
          make run_tests
