---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: License Check and Scan for Viruses

on:
  # Allow manually triggering the workflow
  workflow_dispatch: {}
  # Run on all commits that are pushed to all branches
  push:
    branches:
      - main
      - release-*
  
# Trigger workflow on PRs to all branches
pull_request:
  branches:
    - "*"
  types:
    - opened
    - synchronize
    - reopened

# Trigger workflow when enqueued to a merge group
merge_group:

# Only run at most 1 workflow concurrently per PR, unlimited for branches
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read          # needed for actions/checkout

jobs:
  scan-vulnerabilities:
    name: Scan for vulnerabilities
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      OUTPUT_FILE: e2e-tests/trivy/trivy-fs-report.csv
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trivy (Filesystem)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "fs"
          scan-ref: "."
          format: "template"
          template: "@e2e-tests/trivy/trivy-scan-report.tpl"
          output: ${{ env.OUTPUT_FILE }}
          exit-code: 1
          cache: "false"

      - name: Upload evidence
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: trivy-fs-report
          path: ${{ env.OUTPUT_FILE }}

  scan-viruses:
    name: Scan for viruses
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      OUTPUT_FILE: antivirus-report.txt
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.1

      - name: ClamAV
        run: |
          docker run --rm \
          --mount type=bind,source=./,target=/scandir \
          clamav/clamav:stable \
          clamscan --recursive --log=/scandir/${{ env.OUTPUT_FILE }} \
          /scandir

          if [ $? -ne 0 ]; then
            exit 1
          fi
          sudo chown $USER:$USER ${{ env.OUTPUT_FILE }}

      - name: Upload evidence
        if: always()
        uses: actions/upload-artifact@v4.4.3
        with:
          name: antivirus-report
          path: ${{ env.OUTPUT_FILE }}

  check-license:
    name: Check License
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4