---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Code Analysis] Coverity (C/C++)"
run-name: "[Code Analysis] Coverity (C/C++)"

on:
  workflow_call: {}
  workflow_dispatch: {}
  pull_request:
    branches:
      - main
      - release-*
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main
      
  # Trigger workflow when enqueued to a merge group
  # (must be under 'on')
  merge_group: {}

permissions: {}

# Only run at most 1 workflow concurrently per PR or per branch to keep costs down
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  detect-languages:
    name: "Detect Changed Languages (C/C++)"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      run-analysis: ${{ steps.detect-langs.outputs.run-analysis }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0 # Fetch all history for accurate diff

      - name: "Detect changed languages"
        id: detect-langs
        run: |
          if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]; then
            git fetch origin main:main
            echo "Fetched main branch"
          fi
          changed_files=$(git diff --name-only main...$GITHUB_SHA -- '*.h' '*.hpp' '*.c' '*.cpp' || true)
          echo "Performed git diff"

          if [ -z "$changed_files" ]; then
            echo "No relevant changed files detected."
            echo "run-analysis=false" >> $GITHUB_OUTPUT
            exit 0
          else 
            run_analysis=true
          fi

          echo "Changed files:"
          echo "$changed_files"
          echo "Run analysis:"
          echo "$run_analysis"
          echo "run-analysis=$run_analysis" >> $GITHUB_OUTPUT

  coverity-scan:
    name: "Coverity Scan"
    # if: ${{ needs.detect-languages.outputs.run-analysis == 'true' }}
    # needs: detect-languages
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: "Setup dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends cmake curl g++ git libeigen3-dev libgtest-dev make \
          pkg-config python3-dev pybind11-dev python3-pip python3-scipy python-is-python3 libopencv-dev python3-venv
          pip3 install -r .github/resources/coverity-requirements.txt
      
      - name: "Debug COVERITY_TOKEN"
        run: |
          if [ -z "$COVERITY_TOKEN" ]; then
            echo "COVERITY_TOKEN is not set"
            exit 1
          else
            echo "COVERITY_TOKEN is set"
          fi
        env:
          COVERITY_TOKEN: ${{ secrets.COVERITY_TOKEN }}

      - name: "Download Coverity Scan Tool"
        run: |
          wget --quiet https://scan.coverity.com/download/linux64 \
          --post-data "token=${{ secrets.COVERITY_TOKEN }}&project=${{ secrets.COVERITY_PROJECT }}" \
          -O coverity_tool.tgz
          mkdir cov-analysis
          tar xzf coverity_tool.tgz --strip-components=1 -C cov-analysis

      - name: "Build code manually"
        run: |
          #WIP

      # - name: Build with Coverity Analysis
      #   run: |
      #     # mkdir build && cd build
      #     # export PKG_CONFIG_PATH="/opt/intel/dlstreamer/gstreamer/lib/pkgconfig:${PKG_CONFIG_PATH}"
      #     # ../cov-analysis/bin/cov-build --dir cov-int cmake -DENABLE_PAHO_INSTALLATION=ON -DENABLE_RDKAFKA_INSTALLATION=ON -DENABLE_VAAPI=ON -DENABLE_SAMPLES=ON ..
      #     # ../cov-analysis/bin/cov-build --dir cov-int make -j$(nproc)

      # - name: Create tarball for upload
      #   run: |
      #     tar czf coverity-output.tgz -C build cov-int

      # - name: Upload to Coverity Scan
      #   run: |
      #     curl --form token=${{ secrets.COVERITY_TOKEN }} \
      #          --form email=${{ secrets.COVERITY_EMAIL }} \
      #          --form file=@coverity-output.tgz \
      #          --form version="`date +%Y%m%d%H%M%S`" \
      #          --form description="GitHub Action upload" \
      #          https://scan.coverity.com/builds?project=${{ secrets.COVERITY_PROJECT }}

      - name: "Clean runner"
        if: always()
        run: |
          if [ -n "$GITHUB_WORKSPACE" ] && [ -d "$GITHUB_WORKSPACE" ]; then
            find "$GITHUB_WORKSPACE" -type f -exec chmod u+rw {} \;
            find "$GITHUB_WORKSPACE" -mindepth 1 -delete
          else
            echo "Error: GITHUB_WORKSPACE is not set or is not a directory" >&2
            exit 1
          fi
