---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Pre-Merge Migration Tests Checking

on:
  workflow_dispatch:
    inputs:
      run_type:
        description: 'Specify the type of run'
        required: true
        default: 'manual'

  push:
    branches:
      - ci/migration

  pull_request:
    branches:
      - main

  # Trigger workflow when enqueued to a merge group
  merge_group:

# Only run at most 1 workflow concurrently per PR, unlimited for branches
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

permissions:
  contents: read

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      RUN_TYPE: ${{ github.event.inputs.run_type || '' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup environment
        shell: bash
        run: |
          chmod +x .github/scripts/check_and_set-build-type.sh
          .github/scripts/check_and_set-build-type.sh
