---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge CI Pipeline

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - release-*
  workflow_dispatch:

permissions:
  contents: read          # needed for actions/checkout
  pull-requests: read     # needed for gh pr list
  issues: write           # needed to post PR comment

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      toplevel_changed: ${{ steps.filter.outputs.toplevel }}
      autocalibration_changed: ${{ steps.filter.outputs.autocalibration }}
      controller_changed: ${{ steps.filter.outputs.controller }}
      percebro_changed: ${{ steps.filter.outputs.percebro }}
    steps:
      - uses: actions/checkout@v4
      - name: Set paths filter
        id: filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
        with:
          filters: |
            toplevel:
              - 'docs/**'
            autocalibration:
              - 'autocalibration/docs/**'
            controller:
              - 'controller/docs/**'
            percebro:
              - 'percebro/docs/**'

  build_toplevel:
    needs: filter
    if: ${{ needs.filter.outputs.toplevel_changed == 'true' }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@b39f8770ac653e73001e07f9f47028e1d590be5c
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}

  build_autocalibration:
    needs: [filter, build_toplevel]
    if: ${{ (needs.filter.outputs.autocalibration_changed == 'true') || (needs.filter.outputs.toplevel_changed == 'true') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@b39f8770ac653e73001e07f9f47028e1d590be5c
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: autocalibration

  build_controller:
    needs: [filter, build_toplevel]
    if: ${{ (needs.filter.outputs.controller_changed == 'true') || (needs.filter.outputs.toplevel_changed == 'true') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@b39f8770ac653e73001e07f9f47028e1d590be5c
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: controller

  build_percebro:
    needs: [filter, build_toplevel]
    if: ${{ (needs.filter.outputs.percebro_changed == 'true') || (needs.filter.outputs.toplevel_changed == 'true') }}
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@b39f8770ac653e73001e07f9f47028e1d590be5c
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: percebro
