name: Publish Docs

on:
  workflow_dispatch:

permissions:
  contents: read          # needed for actions/checkout
  pull-requests: read     # needed for gh pr list
  issues: write           # needed to post PR comment

jobs:
  build_toplevel:
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@14f9aea7650263a4b4d864d242dd4c31698cbb75
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}

  build_autocalibration:
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@14f9aea7650263a4b4d864d242dd4c31698cbb75
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: autocalibration

  build_controller:
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@14f9aea7650263a4b4d864d242dd4c31698cbb75
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: controller

  build_percebro:
    uses: open-edge-platform/orch-ci/.github/workflows/publish-documentation.yml@14f9aea7650263a4b4d864d242dd4c31698cbb75
    secrets:
      SYS_ORCH_GITHUB: ${{ secrets.SYS_ORCH_GITHUB }}
      DOC_AWS_ACCESS_KEY_ID: ${{ secrets.DOC_AWS_ACCESS_KEY_ID }}
      DOC_AWS_SECRET_ACCESS_KEY: ${{ secrets.DOC_AWS_SECRET_ACCESS_KEY }}
    with:
      docs_directory: percebro
