---
# SPDX-FileCopyrightText: (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Tests] All Tests"
run-name: "[Tests] All Tests"

on:
  workflow_dispatch:
    inputs:
      cleanup:
        description: "Cleanup before running ALL tests"
        required: false
        default: false
        type: boolean
      ref:
        description: "SceneScape ref to test against"
        required: false
        default: ""
        type: string
  workflow_call:
    inputs:
      ref:
        description: "SceneScape ref to test against"
        required: false
        default: ""
        type: string
      save_artifacts:
        description: "Save artifacts from tests"
        required: false
        default: true
        type: boolean
      cleanup:
        description: "Cleanup before running ALL tests"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
      - release-*

# Only run at most 1 workflow concurrently per pushed commit
concurrency:
  group: ${{ github.workflow }}-${{ github.sha || github.ref }}-${{ inputs.ref || 'default' }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1
  SUPASS: demo

permissions:
  contents: read

jobs:
  run_functional_tests:
    runs-on: [all]
    name: "Functional Tests"
    timeout-minutes: 90
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Functional Tests
        run: |
          make clean-all
          mkdir test_data
          make run_functional_tests > test_data/functional_tests.log 2>&1

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_non_functional_tests:
    runs-on: [all]
    name: "Non-Functional Tests"
    timeout-minutes: 20
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Non-Functional Tests
        run: |
          make clean-all
          mkdir test_data
          make run_non_functional_tests > test_data/non_functional.log 2>&1

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_metric_tests:
    runs-on: [all]
    name: "Metric Tests"
    timeout-minutes: 30
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Metric Tests
        run: |
          make clean-all
          mkdir test_data
          make run_metric_tests > test_data/metrics.log 2>&1

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_ui_tests:
    runs-on: [all]
    name: "UI Tests"
    timeout-minutes: 120
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run UI Tests
        run: |
          make clean-all
          mkdir test_data
          make run_ui_tests > test_data/ui_tests.log 2>&1

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_unit_tests:
    runs-on: [all]
    name: "Unit Tests"
    timeout-minutes: 20
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event_name == 'push' || github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Unit Tests
        run: |
          make clean-all
          mkdir test_data
          make run_unit_tests > test_data/unit_tests.log 2>&1

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_release_tests:
    runs-on: [all]
    name: "Release Tests"
    timeout-minutes: 60
    steps:
      - name: Remove test_data folder
        run: |
          sudo rm -rf test_data || true

      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Release Tests
        run: |
          make clean-all
          mkdir test_data
          make setup_tests
          make -C tests release-tests > test_data/release_tests.log 2>&1

      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts

      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  generate_report:
    needs:
      [
        run_functional_tests,
        run_non_functional_tests,
        run_metric_tests,
        run_ui_tests,
        run_unit_tests,
        run_release_tests,
      ]
    runs-on: ubuntu-latest
    name: "Generate Test Report"
    if: always()
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
          # ref: ${{ inputs.ref }}
      - name: Download All Test Artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
        with:
          merge-multiple: true
      - name: Get all test cases from test files
        id: get_test_cases
        run: |
          grep -rh "# NEX-T" tests/ | sed -n 's/^\([^:]*\):.*# \(NEX-T[0-9]*\).*/\2 \1/p' | sort > all_test_cases.txt
      - name: Get Tests results
        id: get_test_results
        shell: bash
        run: |
          set +e
          touch test_results_summary.txt
          log_files=("test_data/metrics.log" "test_data/non_functional.log" "test_data/functional_tests.log" "test_data/ui_tests.log" "test_data/unit_tests.log" "test_data/release_tests.log")
          for log_file in "${log_files[@]}"; do
            grep -Erh "NEX-T.*: (PASS|FAIL)" $log_file \
            | sed 's/^[[:space:]]*\(NEX-T[0-9]*\)[^:]*\(: \(PASS\|FAIL\)\)\(ED\)\?/\1\2/' \
            >> test_results_summary.txt
          done
          cat test_results_summary.txt | sort -u -o test_results_summary.txt
      - name: Setup Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          pip install -r tools/test_report/requirements.txt
      - name: Get current date
        run: echo "CURRENT_DATE=$(date +"%Y_%m_%d")" >> $GITHUB_ENV
      - name: Generate Test Results Report
        run: |
          python3 tools/test_report/test_report.py all_test_cases.txt test_results_summary.txt $CURRENT_DATE
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: report-html
          overwrite: true
          path: |
            ${{ env.CURRENT_DATE }}_test_report.html
