---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

name: "Tests"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main
      - release-*
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

permissions:
  contents: read # needed for actions/checkout

jobs:
  run-all-tests:
    name: "Run All Tests"
    runs-on: ubuntu-latest
    env:
      SUPASS: "demo"
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.13"

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates unzip curl git vim jq moreutils git-lfs cifs-utils curl gnupg unzip sshpass make

      - name: "Cache Python Virtualenv"
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('.github/resources/requirements.txt') }}
          restore-keys: |
            venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}

      - name: Run Certificates Initialization
        run: |
          make init-secrets

      - name: Build scene_common
        run: |
          git status
          make -C scene_common

      - name: Run All Tests
        run: |
          rm -rf venv
          python3 -m venv venv
          source "$PWD/venv/bin/activate"
          echo "$PWD/venv/bin" >> "$GITHUB_PATH"
          pip install --upgrade pip
          pip install -r .github/resources/requirements.txt
          make run_tests

      - name: Rename logs to remove colons
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install rename
          find . -wholename "**/test_data/**/*.log" -exec rename 's/:/-/g' {} +

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: tests-reports
          path: |
            tests/**/test_reports/**/*.html
            tests/**/test_reports/**/*.xml

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: tests-logs
          path: |
            **/test_data/**/*.log

  run-bat:
    name: "Run Basic Acceptance Tests"
    runs-on: ubuntu-latest
    env:
      SUPASS: "demo"
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install ca-certificates unzip curl git vim jq moreutils git-lfs cifs-utils curl gnupg unzip sshpass make

      - name: Run BAT
        run: |
          make run_basic_acceptance_tests

      - name: Rename logs to remove colons
        if: always()
        run: |
          sudo apt-get update
          sudo apt-get install rename
          find . -wholename "**/test_data/**/*.log" -exec rename 's/:/-/g' {} +

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: bat-reports
          path: |
            tests/**/test_reports/**/*.html
            tests/**/test_reports/**/*.xml

      - name: Upload Test Logs
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: bat-logs
          path: |
            **/test_data/**/*.log
