---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Tests] Basic Acceptance Tests"
run-name: "[Tests] Basic Acceptance Tests"

on:
  workflow_dispatch:
    inputs:
      cleanup:
        description: "Cleanup before running BAT tests"
        required: false
        default: false
        type: boolean
      timeout:
        description: "Timeout for the job in minutes"
        required: false
        type: number
        default: 60
  pull_request:
    branches:
      - main
      - release-*
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
  push:
    branches:
      - main
      - release-*

  # Trigger workflow when enqueued to a merge group
  # (must be under 'on')
  merge_group: {}

# Only run at most 1 workflow concurrently per PR or per branch to keep costs down
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1
  SUPASS: demo

permissions:
  contents: read

jobs:

  run-basic-acceptance-tests:
    name: "Run Basic Acceptance Tests"
    runs-on: [npm]
    timeout-minutes: ${{ fromJSON(inputs.timeout || '60') }}
    steps:
      - name: "Install NPM"
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
