# SPDX-FileCopyrightText: (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Tests] All Tests"
run-name: "[Tests] All Tests"

on:
  workflow_dispatch:
    inputs:
      cleanup:
        description: "Cleanup before running ALL tests"
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      ref:
        description: "SceneScape ref to test against"
        required: false
        default: ""
        type: string
      save_artifacts:
        description: "Save artifacts from tests"
        required: false
        default: true
        type: boolean
      cleanup:
        description: "Cleanup before running ALL tests"
        required: false
        default: false
        type: boolean
  push:
    branches:
      - main
      - release-*

# Only run at most 1 workflow concurrently per pushed commit
concurrency:
  group: ${{ github.workflow }}-${{ github.sha || github.ref }}-${{ inputs.ref || 'default' }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1
  SUPASS: demo

permissions:
  contents: read

jobs:
  run_functional_tests:
    runs-on: [all]
    name: 'Functional Tests (${{ fromJSON(''{"functional-scenes":"Scenes",
      "functional-sensors":"Sensors","functional-cameras":"Cameras",
      "functional-mqtt":"MQTT","functional-objects":"Objects",
      "functional-generic":"Generic"}'')[matrix.group] }})'
    timeout-minutes: 55
    strategy:
      fail-fast: false
      matrix:
        group:
          ${{ fromJSON('["functional-scenes","functional-sensors","functional-cameras",
          "functional-mqtt","functional-objects","functional-generic"]') }}
    steps:
      - name: Remove test_data folder
        run: sudo rm -rf test_data || true
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"
      - name: Run Setup
        uses: ./.github/actions/setup-env
      - name: Run Functional Tests
        run: |
          make clean-all
          make run_functional_tests FUNC_GROUP=${{ matrix.group }}
      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts
        with:
          name: ${{ matrix.group }}
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_non_functional_tests:
    runs-on: [all]
    name: "Non-Functional Tests"
    timeout-minutes: 25
    steps:
      - name: Remove test_data folder
        run: sudo rm -rf test_data || true
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"
      - name: Run Setup
        uses: ./.github/actions/setup-env
      - name: Run Non-Functional Tests
        run: |
          make clean-all
          make run_non_functional_tests
      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts
        with:
          name: non-functional
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_metric_tests:
    runs-on: [all]
    name: "Metric Tests"
    timeout-minutes: 25
    steps:
      - name: Remove test_data folder
        run: sudo rm -rf test_data || true
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"
      - name: Run Setup
        uses: ./.github/actions/setup-env
      - name: Run Metric Tests
        run: |
          make clean-all
          make run_metric_tests
      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts
        with:
          name: metric
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_ui_tests:
    runs-on: [all]
    name: 'UI Tests (${{ fromJSON(''{"ui-scenes":"Scenes",
      "ui-sensors":"Sensors","ui-cameras":"Cameras",
      "ui-mqtt":"MQTT","ui-objects":"Objects",
      "ui-generic":"Generic"}'')[matrix.group] }})'
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        group: ${{ fromJSON('["ui-scenes","ui-sensors","ui-cameras",
          "ui-mqtt","ui-objects","ui-generic"]') }}
    steps:
      - name: Remove test_data folder
        run: sudo rm -rf test_data || true
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"
      - name: Run Setup
        uses: ./.github/actions/setup-env
      - name: Run UI Tests
        run: |
          make clean-all
          make run_ui_tests UI_GROUP=${{ matrix.group }}
      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts
        with:
          name: ${{ matrix.group }}
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup

  run_unit_tests:
    runs-on: [all]
    name: "Unit Tests"
    timeout-minutes: 20
    steps:
      - name: Remove test_data folder
        run: sudo rm -rf test_data || true
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
          ref: ${{ inputs.ref }}

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"
      - name: Run Setup
        uses: ./.github/actions/setup-env
      - name: Run Unit Tests
        run: |
          make clean-all
          make run_unit_tests
      - name: Upload Logs and Reports
        if: always() && (!contains(toJSON(inputs), 'save_artifacts') || inputs.save_artifacts)
        uses: ./.github/actions/upload-artifacts
        with:
          name: unit
      - name: Cleanup
        if: always()
        uses: ./.github/actions/cleanup
