---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Tests] All Tests"
run-name: "[Tests] All Tests"

on:
  schedule:
    - cron: "0 2 * * *" # Runs daily at 2:00 AM UTC
  workflow_dispatch:
    inputs:
      cleanup:
        description: "Cleanup before running ALL tests"
        required: false
        default: false
        type: boolean
      timeout:
        description: "Timeout for the job in minutes"
        required: false
        type: number
        default: 90
  push:
    branches:
      - main
      - release-*

  # Trigger workflow when enqueued to a merge group
  # (must be under 'on')
  merge_group: {}

# Only run at most 1 workflow concurrently per PR or per branch to keep costs down
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DOCKER_BUILDKIT: 1
  SUPASS: ${{ secrets.SUPASS }}
  BUILD_TYPE: DAILY

permissions:
  contents: read

jobs:
  run_basic_acceptance_tests:
    runs-on: [all]
    name: "Basic Acceptance Tests"
    timeout-minutes: ${{ github.event.inputs.timeout || 90 }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Basic Acceptance Tests
        run: make run_basic_acceptance_tests

      - name: Cleanup
        uses: ./.github/actions/cleanup

  run_functional_tests:
    runs-on: [all]
    name: "Functional Tests"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Functional Tests
        run: make run_functional_tests

      - name: Cleanup
        uses: ./.github/actions/cleanup

  run_non_functional_tests:
    runs-on: [all]
    name: "Non-Functional Tests"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Non-Functional Tests
        run: make run_non_functional_tests

      - name: Cleanup
        uses: ./.github/actions/cleanup

  run_metric_tests:
    runs-on: [all]
    name: "Metric Tests"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Metric Tests
        run: make run_metric_tests

      - name: Cleanup
        uses: ./.github/actions/cleanup

  run_ui_tests:
    runs-on: [all]
    name: "UI Tests"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run UI Tests
        run: make run_ui_tests

      - name: Cleanup
        uses: ./.github/actions/cleanup


  run_unit_tests:
    runs-on: [all]
    name: "Unit Tests"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: "Remove all Docker images"
        if: ${{ github.event.inputs.cleanup == 'true' }}
        uses: ./.github/actions/cleanup
        with:
          system-prune: "true"

      - name: "Run Setup"
        uses: ./.github/actions/setup-env

      - name: Run Unit Tests
        run: make run_unit_tests

      - name: Cleanup
        uses: ./.github/actions/cleanup

  collect-artifacts:
    name: "Collect Logs and Reports"
    needs:
      - run_basic_acceptance_tests
      - run_functional_tests
      - run_non_functional_tests
      - run_metric_tests
      - run_ui_tests
      - run_unit_tests
    runs-on: [all]
    if: always()
    steps:
      - name: Rename logs to remove colons
        run: |
          set +e # Ignore errors if no logs are found
          find . -type f -path "**/test_data/*.log" | while read -r file; do
            newfile="$(dirname "$file")/$(basename "$file" | tr ':' '-')"
            if [ "$file" != "$newfile" ]; then
              mv "$file" "$newfile"
            fi
          done
          exit 0

      - name: Upload Test Reports
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: tests-reports
          path: |
            tests/**/test_reports/**/*.html
            tests/**/test_reports/**/*.xml

      - name: Upload Test Logs
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: tests-logs
          path: |
            **/test_data/**/*.log

      - name: Cleanup
        uses: ./.github/actions/cleanup
