---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "Weekly Build Images"
run-name: "Weekly Build Images"

on:
  schedule:
    - cron: "59 6 * * 3" # Each Wednesday at 06:59 UTC (Tuesday 11:59pm PST)
  workflow_dispatch: {}
permissions: {}

jobs:
  build-tag-and-push:
    name: "Build Images, Tag and Push"
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.determine-tag.outputs.image_tag }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1

      - name: "Log in to GHCR"
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Checkout code"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: false

      - name: "Build images"
        run: |
          set -e
          for dir in scene_common autocalibration controller manager; do
            cd $dir
            make
            cd ..
          done

      - name: "Determine Image Tag"
        id: determine-tag
        run: |
          version=""
          if [ -f version.txt ]; then
            version=v$(cat version.txt | tr -d ' \n')
          fi
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            commit_hash=$(git rev-parse --short HEAD)
            tag="${version:+$version-}$commit_hash"
            echo "image_tag=$tag" >> $GITHUB_OUTPUT
          else
            date_tag=$(date -u +'%Y%m%d')
            tag="${version:+$version-}$date_tag"
            echo "image_tag=$tag" >> $GITHUB_OUTPUT
          fi

      - name: "Tag images"
        run: |
          docker tag scenescape-camcalibration:latest ghcr.io/${{ github.repository }}/scenescape-camcalibration:${{ steps.determine-tag.outputs.image_tag }}
          docker tag scenescape-controller:latest ghcr.io/${{ github.repository }}/scenescape-controller:${{ steps.determine-tag.outputs.image_tag }}
          docker tag scenescape-manager:latest ghcr.io/${{ github.repository }}/scenescape-manager:${{ steps.determine-tag.outputs.image_tag }}

      - name: "Push images"
        run: |
          docker push ghcr.io/${{ github.repository }}/scenescape-camcalibration:${{ steps.determine-tag.outputs.image_tag }}
          docker push ghcr.io/${{ github.repository }}/scenescape-controller:${{ steps.determine-tag.outputs.image_tag }}
          docker push ghcr.io/${{ github.repository }}/scenescape-manager:${{ steps.determine-tag.outputs.image_tag }}

  scan-and-sign:
    name: "Scan and Sign Images"
    runs-on: ubuntu-latest
    needs: build-tag-and-push
    steps:
      - name: "🔍 [scenescape-camcalibration] Scan Docker image with Trivy"
        id: scenescape-camcalibration
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@65fc743e0c69b8529188b89dede3acfe2897b2e0
        with:
          scan_target: "ghcr.io/${{ github.repository }}/scenescape-camcalibration:${{ needs.build-tag-and-push.outputs.image_tag }}"
          severity: "HIGH,CRITICAL"
          scan_type: image
          format: table
          scan-scope: all
          timeout: 20m
          ignore_unfixed: true

      - name: "🔍 [scenescape-controller] Scan Docker image with Trivy"
        id: scenescape-controller
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@65fc743e0c69b8529188b89dede3acfe2897b2e0
        with:
          scan_target: "ghcr.io/${{ github.repository }}/scenescape-controller:${{ needs.build-tag-and-push.outputs.image_tag }}"
          severity: "HIGH,CRITICAL"
          scan_type: image
          format: table
          scan-scope: all
          timeout: 20m
          ignore_unfixed: true

      - name: "🔍 [scenescape-manager] Scan Docker image with Trivy"
        id: scenescape-manager
        uses: open-edge-platform/orch-ci/.github/actions/security/trivy@65fc743e0c69b8529188b89dede3acfe2897b2e0
        with:
          scan_target: "ghcr.io/${{ github.repository }}/scenescape-manager:${{ needs.build-tag-and-push.outputs.image_tag }}"
          severity: "HIGH,CRITICAL"
          scan_type: image
          format: table
          scan-scope: all
          timeout: 20m
          ignore_unfixed: true

      - name: "Fail if vulnerabilities > 0 in Trivy results"
        run: |
          file=$(ls security-results/trivy/trivy-results-* | head -n 1)
          cat $file
          vuln_count=$(awk '/│/ && /Vulnerabilities/ {next} /│/ {gsub(/ /, "", $0); split($0, cols, "│"); print cols[4]}' "$file" | grep -v '-' | head -n 1)

          echo "Found vulnerability count: $vuln_count"

          if [[ "$vuln_count" != "0" ]]; then
            echo "❌ Vulnerabilities found: $vuln_count"
            exit 1
          else
            echo "✅ No vulnerabilities found."
          fi
        shell: bash

      - name: Install Cosign
        uses: sigstore/cosign-installer@398d4b0eeef1380460a10c8013a76f728fb906ac # v3.9.1

      - name: Sign Docker images using Cosign (keyless)
        run: |
          cosign sign ghcr.io/${{ github.repository }}/scenescape-camcalibration:${{ needs.build-tag-and-push.outputs.image_tag }}
          cosign sign ghcr.io/${{ github.repository }}/scenescape-controller:${{ needs.build-tag-and-push.outputs.image_tag }}
          cosign sign ghcr.io/${{ github.repository }}/scenescape-manager:${{ needs.build-tag-and-push.outputs.image_tag }}

  cleanup:
    name: "Clean up"
    runs-on: ubuntu-latest
    needs: scan-and-sign
    steps:
      - name: Clean up
        if: always()
        run: |
          docker system prune -a --volumes || true
