---
# SPDX-FileCopyrightText: (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: "[Tests] Zephyr Traceability"
run-name: "[Tests] Zephyr Traceability"

on:
  schedule:
    - cron: "0 3 * * *" # Every day at 3:00 AM UTC
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  check-zephyr-mapping:
    name: "Check Pytest to Zephyr Mapping"
    runs-on: [all] # Jira is only reachable from self-hosted runners
    timeout-minutes: 60
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: "Set up Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
          check-latest: true

      - name: "Create pytest environment"
        run: |
          make setup-pytest

      - name: "Check pytest to Zephyr mapping"
        env:
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_TEAM: ${{ vars.JIRA_TEAM }}
          JIRA_PROJECT: ${{ vars.JIRA_PROJECT }}
          JIRA_API_BASE: ${{ vars.JIRA_API_BASE }}
          ZEPHYR_API_BASE: ${{ vars.ZEPHYR_API_BASE }}
          ZEPHYR_FOLDERS: ${{ vars.ZEPHYR_FOLDERS }}
        run: |
          make check-zephyr-mapping
