# SPDX-FileCopyrightText: (C) 2021 - 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

IMAGE := scenescape-clusterizer

include ../common.mk

.PHONY: test-build
test-build:
	$(MAKE) IMAGE="scenescape-clusterizer-test" TARGET="scenescape-clusterizer-test"
