#!/bin/bash

# SPDX-FileCopyrightText: (C) 2023 - 2025 Intel Corporation
# SPDX-License-Identifier: LicenseRef-Intel-Edge-Software
# This file is licensed under the Limited Edge Software Distribution License Agreement.

TEST_NAME="NEX-T10493"
FILES=(rvfiles uifiles)
TEMP_EXT="tmp"
STATUS="${#FILES[@]}"

echo "Executing: ${TEST_NAME}"
# Change the directory to the base folder
cd "$(dirname "$0")"/../../ && pwd

for file in "${FILES[@]}"; do

    if [ "$file" == "rvfiles" ]; then
        LOC_DIR="controller/docker"
    else
        LOC_DIR="manager/docker"
    fi

    mv "$LOC_DIR/Makefile.$file" "$LOC_DIR/Makefile.$file.$TEMP_EXT"

    echo "Generate the latest Makefile.$file"
    make -C $LOC_DIR "Makefile.$file"

    if ! diff "$LOC_DIR/Makefile.$file" "$LOC_DIR/Makefile.$file.$TEMP_EXT"; then
        echo "File '$LOC_DIR/Makefile.$file' should be regenerated!"
    else
        echo "File '$LOC_DIR/Makefile.$file' is up-to-date."
        ((STATUS--))
    fi

    mv "$LOC_DIR/Makefile.$file.$TEMP_EXT" "$LOC_DIR/Makefile.$file"
done

if [[ $STATUS -eq 0 ]] ; then
    echo "${TEST_NAME}: PASS"
else
    echo "${TEST_NAME}: FAIL"
fi

exit "$STATUS"
